---
- name: awx test
  hosts: abc
  remote_user: ubuntu
  tasks:
  - name: list files in home directory
    command: ls -lht ~/
  - name: Creates directory
    file:
      path: ~/www
      state: directory
  - name: create credential file
    copy:
      src: credentials.ini
      dst: ~/www/credentials.ini
